name = "Flipwitch Forbidden Sex Hex"
home = "https://discord.com/channels/1085716850370957462/1303773960873185320"
default_url = "https://github.com/Witchybun/FlipwitchAPClient/releases/download/{{version}}/flipwitch.apworld"

[versions]
"0.2.8" = {}
